[bot]
data_folder = "data"
extensions = [
	"aethersprite.extensions.base._all",
]
help_command = "aehelp"
token = "SOMEREALLYLONGSTRINGTHATDISCORDGIVESYOU"
owner = "haliphax#4859"

[webapp]
proxies = 1

	[webapp.flask]
	SERVER_NAME = "localhost:5000"
	SERVER_HOST = "0.0.0.0"
	SERVER_PORT = 5000
